### ISSUE TITLE
Diagram CI not working as expected

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/vre#122]
[minor bug]
The diagram CI tries to push to main directly, but main is protected. An example: https://github.com/vre-hub/vre/actions/runs/4916815447/jobs/8781065068#step:3:180

**Comment by goseind** [comment]
I will resolve this later, its a bit tricky but since this is just a "for fun" feature it's not important 😄

**Comment by garciagenrique** [comment]
Closing, ref to #153
