### ISSUE TITLE
Manage Rucio by flux

### ISSUE THREAD

**Issue by egazzarr** [vre-hub/vre#138]
- [x] create 'rucio-vre' namespace
- [x] create rucio-vre repo in flux repo 
- [x] rucio server using LoadBalancer As a Service
- [ ] Check rucio server/ui/daemons versions - use one of the latests

that would allow:
 - [x] Re deploy a stable version of Rucio

**Comment by garciagenrique** [comment]
Dividing this Issue into two, separating the tasks into high-priority, and mid-priority

**Comment by egazzarr** [comment]
everything is working in the flux gitops way

**Comment by garciagenrique** [comment]
solved with commits bd61e698c94d0c07f1e79f6d8b48983c9e14e72e to b8c1d8a4150add3ff97e9310dda25d71430e751b

**Comment by garciagenrique** [comment]
Last tasklist moved to #165
