### ISSUE TITLE
`create-diagram` action not working correctly

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/vre#153]
It's a very cool feature, but currently it's failing on the repo (creating an extra action + email, i.e., noise that can be just avoided).

Having a look to the documentation of the action, every time the diagram it's added, a new commit is added to the repo too. IMHO, I will avoid under any circumstances this feature, as it will just pollute the git history. (And once we would have reached good dev practises  - on the very close future-, this will be not idea). According to the doc, this can be avoid, but then I don't know how the diagram could be added to the repository/README.

@goseind I let you investigate the action + how not to create an extra commit. 

Taking out the action workflow file + the outdated diagram.

**Comment by goseind** [comment]
Feature removed.
