### ISSUE TITLE
Keep `tf` for the K8s openstack configuration

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/vre#159]
Move all the rest of services to `flux`

**Comment by goseind** [comment]
See #179 for jhub, which is linked to the #21 issue in the project board.

**Comment by goseind** [comment]
Cross-referencing https://github.com/vre-hub/vre/pull/182#issuecomment-1649374776 ℹ️

**Comment by goseind** [comment]
I suggest keeping these Terraform files and not risking problems migrating them to Flux at the moment. If changes are needed to these resources later, they can be reapplied with Flux and taken out of Terraform (just run [`state rm`](https://developer.hashicorp.com/terraform/cli/commands/state/rm) on these resources).

**Comment by egazzarr** [comment]
Yes agree we should keep the Terraform files.
