### ISSUE TITLE
Resolve conflicts between JupyterHub config and vre-singeluser image

### ISSUE THREAD

**Issue by goseind** [vre-hub/vre#192]
This issue describes the problems ⚠️ 
* the rucio extension is setup with OIDC token, but scopes are not loading
* the rucio cli client asks for a manual token configuration

And proposed solutions for the rucio OIDC functionality with the new flux/single user image 🚦 
* clean discrepancies/overlapping environment variables in both config and image
* remove/check the certificate rucio is using 

Further ideas are 💡 
* move some configuration to the hub/single user image (away from the config), e.g. a custom Python package stored externally

**Comment by garciagenrique** [comment]
Closing thanks to latests merged and referenced PRs.

@goseind feel free to open an issue not to forget your last point!
 
> Further ideas are 💡
>
> move some configuration to the hub/single user image (away from the config), e.g. a custom Python package stored externally
